theme: jekyll-theme-slate
title: LACHLAN STEWART
description: ### [About Me](https://lachlanstewart.github.io/About-Me/ "Who am I?")       |    [Portfolio](https://lachlanstewart.github.io/Portfolio/ "Like a resume, but cooler!")       |    [Tech](https://lachlanstewart.github.io/Tech/ "A summary of my technical skills")     |    [Academics](https://lachlanstewart.github.io/Academics/ "All my classes and favourite coursework in one place")
